version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g serverless
      - npm install

  build:
    commands:
      - echo Building the Next.js application...
      - npm run build
      - echo Packaging the Next.js application for AWS Lambda...
      - serverless package

artifacts:
  files:
    - .serverless/**
  discard-paths: yes
